### ISSUE TITLE
Geneprof 500 response

### ISSUE THREAD

**Issue by erikyao** [dkoslicki/NCATS#134]
When running `test_geneprof_id_to_transcription_factor_gene_symbols` of `tests/QueryGeneProfTestCase`, `QueryGeneProf.geneprof_id_to_transcription_factor_gene_symbols` sometimes returns an empty set due to Genprof's 500 response.

Test code:

```python
ret_set = QueryGeneProf.geneprof_id_to_transcription_factor_gene_symbols(16269)  # 'HMOX1'
```

Debugging message:

> HTTP response status code: 500 for URL:
http://www.geneprof.org/GeneProf/api/gene.info/regulation/binary/by.target/human/16269.json?with-sample-info=true

Cause of 500 reported by Geneprof:

> java.lang.OutOfMemoryError: unable to create new native thread

We may need to add exception-handling code in this case.

**Comment by dkoslicki** [comment]
This issue was moved to RTXteam/RTX#2
